### ISSUE TITLE
support for mathematical programming lanugages

### ISSUE THREAD

**Issue by orthopteroid** [github/linguist#1207]
http://zimpl.zib.de/ specifies a script-like language for different types of numerical optimization problems. I presently have a repro (https://github.com/orthopteroid/hydrolp-a) where I show how to use this language, but github doesn't recognize the language used in the repro. I've named my problem file .zpl

But it occurs to me that there are many other mathematical programming languages out there and so Zimpl may be just one in a group of languages that should be in the linguist/lib/languages.yaml file. Consider, http://www.rpi.edu/dept/math/math-programming/cplex66/sun4x_58/doc/refman/html/appendixE.html Can I suggest a new entry:

```
Mathematical Programming:
  type: programming
  extensions:
# zimpl
  - .zpl
  - .zimpl
# ampl
  - .ampl
# generic formats
  - .mps
  - .lps
  - .lp
```
