### ISSUE TITLE
YAML lexer not handling blocks

### ISSUE THREAD

**Issue by stuartpb** [github/linguist#2563]
Since [this appears to be the repository where we should post syntax highlighting problems](https://github.com/github/linguist/issues/1717), this YAML lexes wrong even though it's syntactically valid:

```yaml
foo:
  thesis:
    There was a sentence here.
  owners:
  - stuartpb
  mechanics:
  - - note: >
        This sentence's apostrophe throws off syntax highlighting below.
    - role: members
    - role: others
    - role: public
    - note: >
        There was a great big blob of text here, great heaping
        chunks of it. Going on for a *paragraph*, with syntax highlighting
        and slashes/decisions and everything. That does not actually
        impact the parsing bug, but it is notable.
  noises:
  - beep
  - bop
  - dootle
  - dop
# The comments are something the lexer still thinks is part of that string.
# It thinks everything is part of the string.
bar:
  thesis:
    There was another sentence here.
  owners:
  - stuartpb
  bestbaz:
    kenny:
      description: Kenny is no longer the best Baz.
  mechanics:
  - - role: kenny
    - drip: ignore me
    - drip: ignore me too
    - note: >
        It's an apostrophe in this block that brings parsing back to normal.
        The intervening text should not have been interpreted as a blue string.
```
