### ISSUE TITLE
Cucumber vs Gherkin

### ISSUE THREAD

**Issue by adamralph** [github/linguist#2859]
``` yaml
Cucumber:
  type: programming
  extensions:
  - .feature
  tm_scope: text.gherkin.feature
  aliases:
  - gherkin
  ace_mode: text
  color: "#5B2063"
```

Something seems off here.

From https://github.com/cucumber/cucumber/wiki/Gherkin :

> Gherkin is the language that Cucumber understands.

This mirrors my understanding. The language is Gherkin. Cucumber is but one framework which uses it. There are others, e.g. SpecFlow.
