### ISSUE TITLE
YAML highlighting broken when colon is inside a quoted string.

### ISSUE THREAD

**Issue by goodevilgenius** [github/linguist#2959]
For example, the following code:

```yaml
foo:
    bar: 'ABC: DEF'
    baz: yes
    quux: 0.5
```

If viewing a yaml file on GitHub ([e.g.](https://github.com/goodevilgenius/pile/blob/gh-pages/_data/oembed.yml), scroll to the bottom, where `'Last Week Tonight with John Oliver: Abortion Laws (HBO)'` is seen), `ABC:` is shown as a quoted string, and the remainder of the line as a bare string. After that line, every subsequent key is highlighted as a quoted string.
