### ISSUE TITLE
to add a syntax in languages.yml...

### ISSUE THREAD

**Issue by jarriztg** [github/linguist#3271]
i need remake the languages id?

example:

```MTML:
  type: markup
  color: "#b7e1f4"
  extensions:
  - ".mtml"
  tm_scope: text.html.basic
  ace_mode: html
  codemirror_mode: htmlmixed
  codemirror_mime_type: text/html
  language_id: 220``` +1
```MUF:
  type: programming
  group: Forth
  extensions:
  - ".muf"
  - ".m"
  tm_scope: none
  ace_mode: forth
  codemirror_mode: forth
  codemirror_mime_type: text/x-forth
  language_id: 219```+1

??

**Comment by jarriztg** [comment]
or i can add my new language in the end file?

**Comment by pchaigno** [comment]
I'm not sure I understand your question. Have you read the [contribution guidelines on adding a new language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language)?

**Comment by jarriztg** [comment]
xBase:
  type: programming
  color: "#403a40"
  aliases:
  - advpl
  - clipper
  - foxpro
  extensions:
  - ".prg"
  - ".ch"
  - ".prw"
  tm_scope: source.harbour
  ace_mode: text
  language_id: 421
Latino:
  type: programming
  color: "#94B0C7"
  extensions:
  - ".lat"
  ace_mode: text
  language_id: 422

**Comment by jarriztg** [comment]
```
xBase:
  type: programming
  color: "#403a40"
  aliases:
  - advpl
  - clipper
  - foxpro
  extensions:
  - ".prg"
  - ".ch"
  - ".prw"
  tm_scope: source.harbour
  ace_mode: text
  language_id: 421
Latino:
  type: programming
  color: "#94B0C7"
  extensions:
  - ".lat"
  ace_mode: text
  language_id: 422
```
