### ISSUE TITLE
Addition: ASP-Core-2

### ISSUE THREAD

**Issue by lorenzleutgeb** [github/linguist#3867]
Even though ["Answer Set Programming"](https://en.wikipedia.org/wiki/Answer_set_programming) is not widely used, I would like to track requests for adding it, specifically [ASP-Core-2 (spec with grammar)](https://www.mat.unical.it/aspcomp2013/files/ASP-CORE-2.03c.pdf) as a language to Linguist.

A corresponding entry in `languages.yml` might look similar to

```yaml
ASP-Core-2:
  type: programming
  extensions:
  - ".lp"
  interpreters:
  - clingo
  - alpha
  ace_mode: prolog
```

We also have an ANTLR-style grammar [floating around](https://github.com/alpha-asp/Alpha/blob/master/src/main/antlr/at/ac/tuwien/kr/alpha/antlr/ASPCore2.g4).
