### ISSUE TITLE
AutoIt is missing lexer

### ISSUE THREAD

**Issue by jbrooksuk** [github/linguist#456]
I'm trying to add AutoIt highlighting to linguist, but I'm being told that `AutoIt is missing lexer` however it's a part of `pygments.rb`

I've added the following to `languages.yml`:

```
AutoIt:
  type: programming
  lexer: autoit
  color: "#6594b9"
  aliases:
    - Autoit
    - AutoIt
    - autoit
    - au3
  primary_extension: .au3
```

But running `bundle exec rake test` just gives me an error. Not being a Ruby guy I'm not sure what's going on?
