### ISSUE TITLE
scss highlighting issue

### ISSUE THREAD

**Issue by burtek** [github/linguist#4647]
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [ ] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Github ([as well as VSCode](https://github.com/microsoft/vscode/issues/81038)) has scss syntax highlighting issue when using nested properties block after shorthand value:

```scss
.button {
    @include fontDemi;

    border: 0 {
        radius: 30px;
    };
    background-color: $buttonColor;
}
```

```scss
.button {
    @include fontDemi;

    border: {
        radius: 30px;
    };
    background-color: $buttonColor;
}
```

I know it's not github's issue, but [atom/language-sass](https://github.com/atom/language-sass) seems dead (and the related issue https://github.com/atom/language-sass/issues/250 is over one year old now) and I was wondering whether github do something with that (i.e. fork that lib and fix this (and possibly more) issues)?
