### ISSUE TITLE
improve Prolog vs. IDL detection (.pro files)

### ISSUE THREAD

**Issue by slayoo** [github/linguist#5053]
Apparently some .pro files are detected as Prolog, while others are given the IDL label.
The latter is related with the IDL/GDL/PV-WAVE language family.

In the GDL project, all .pro files are IDL source code, while they fall in both categories according to github:
- https://github.com/gnudatalanguage/gdl/search?l=prolog
- https://github.com/gnudatalanguage/gdl/search?l=IDL

Would be great to improve consistency (i.e., so that all are detected as IDL).

Likely relevant helper info:
https://github.com/blackducksoftware/ohcount/blob/master/src/parsers/idl_pvwave.rl

HTH,
Sylwester (originaly reported by @EdwardEisenhauer)

**Comment by lildude** [comment]
The `.pro` extension is associated with quite a few different languages and thus relies upon the heuristic:

https://github.com/github/linguist/blob/1df78c248cafa6b414651673846e26e388710df9/lib/linguist/heuristics.yml#L378-L391

... and samples to identify the language based on the content so in order to make things more consistent, we'd need to improve the heuristics and add a few more representative samples.

Please feel free to open a PR to help improve things.

**Comment by slayoo** [comment]
So the current rules are as follows:
```
- extensions: ['.pro']
  rules:
  - language: Proguard
    pattern: '^-(include\b.*\.pro$|keep\b|keepclassmembers\b|keepattributes\b)'
  - language: Prolog
    pattern: '^[^\[#]+:-'
  - language: INI
    pattern: 'last_client='
  - language: QMake
    and:
    - pattern: HEADERS
    - pattern: SOURCES
  - language: IDL
pattern: '^\s*function[ \w,]+$'
```
