### ISSUE TITLE
VBA appearing as TeX

### ISSUE THREAD

**Issue by sancarn** [github/linguist#5219]
I have a [repository](https://github.com/sancarn/stdVBA/search?l=tex) which is displaying some `.cls` files as `TeX` file format. I am uncertain why this is the case but generally speaking VBA/VB6 classes all start with a specific header:

```
VERSION 1.0 CLASS
```

and will contain a line as follows:

```vb
Attribute VB_Name = "<<someName>>"
```

For this reason I feel it should be relatively easy to determine between a `TeX` file and a VBA file. Does anyone know the reason why this is being misidentified.

**Comment by sancarn** [comment]
Related:

* https://github.com/isaacs/github/issues/1868
* https://github.com/github/linguist/pull/4725
* https://github.com/github/linguist/issues/2418

**Comment by sancarn** [comment]
Am I correct in thinking that it is as simple as adding a line here:

https://github.com/github/linguist/blob/1d1e64e39f4a2e723000364670c6ce30c431bf97/lib/linguist/heuristics.yml#L107

```yml
- extensions: ['.cls']
  rules:
  - language: TeX
    pattern: '\\\w+{'
  - language: ObjectScript
    pattern: '^Class\s'
  - language: VBA
  -     pattern: '^VERSION 1.0 CLASS\s'
```

**Comment by Alhadis** [comment]
Kind of. _Adding_ a heuristic is easy, but _writing_ one that's **accurate** and **reliable** is an entirely different matter.

Case-in-point, the TeX heuristic is guilty of your reported issue. It's naïvely matching any file that happens to contain a letter or digit followed by `{`. Specifically:
* `\0{FILE2}` in [`stdClipboard.cls`](https://github.com/sancarn/stdVBA/blob/65e934cb69d7bb102a83c70dccdfb0ee3a969038/src/stdClipboard.cls#L438),
* `\d{5}` in [`stdRegex.cls`](https://github.com/sancarn/stdVBA/blob/940c768326366308c659c4387331f3c047454867/src/stdRegex.cls#L57), and
* `\d{1,2}` in [`stdDate.cls`](https://github.com/sancarn/stdVBA/blob/57996c5b005b1b2b234da5db046628b7b0e3e261/src/WIP/stdDate.cls#L308).

To disambiguate TeX from ObjectScript and VBA, it would've been wiser to specify a list of directives or keywords commonly found in TeX's `.cls` files (even if it's not guaranteed to catch every TeX file). As you can see, something as open-ended as `\w+` is dangerously inaccurate.

I can't propose a replacement without first reading up on TeX's `.cls` files to learn what they are, and what a viable heuristic would be. If you're familiar with that format and comfortable writing regular expressions, we'd [welcome a pull-request](https://github.com/github/linguist/blob/master/CONTRIBUTING.md). 👍

**Comment by sancarn** [comment]
@Alhadis Am I right in thinking that these heuristics calculate the number of matches and then the language with the most matches wins?

I analysed a TeX document found [here](https://latex.js.org/playground.html) and came up with the following list of keywords:

```regex
/\\(documentclass|usepackage|setcounter|title|LaTeX|author|varheartsuit|date|begin|maketitle|end|section|item|texttt|textbackslash|symbol|verb|char|bigskip|noindent|textcelsius|textdegree|ref|TeX|par|newline|dots|slash|subsection|medbreak|fbox|mbox|emph|smallbreak|bigbreak|makebox|framebox|textbf|parbox|llap|rlap|smash|hphantom|vphantom|phantom|marginpar|huge|negthinspace|thinspace|enspace|quad|qquad|hspace|label|aligned|of|raggedleft|frame|setlength|unitlength|put|vector|circle|thicklines|line|thinlines|sqrt|displaystyle|frac|linethickness|multiput|oval|qbezier|int_|infty|hat|text|today|textalpha|textbeta|textgamma|textdelta|textepsilon|textzeta|texteta|texttheta|textiota|textkappa|textlambda|textmu|textnu|textxi|textomikron|textpi|textrho|textsigma|texttau|textupsilon|textphi|textchi|textpsi|textomega|texteuro|textcent|textsterling|pounds|textbaht|textcolonmonetary|textcurrency|textdong|textflorin|textlira|textnaira|textpeso|textwon|textyen|textzerooldstyle|textoneoldstyle|texttwooldstyle|textthreeoldstyle|textfouroldstyle|textfiveoldstyle|textsixoldstyle|textsevenoldstyle|texteightoldstyle|textnineoldstyle|textperthousand|perthousand|textpertenthousand|textonehalf|textthreequarters|textonequarter|textfractionsolidus|textdiv|texttimes|textminus|textpm|textsurd|textlnot|textasteriskcentered|textonesuperior|texttwosuperior|textthreesuperior|textleftarrow|textuparrow|textrightarrow|textdownarrow|checkmark|textreferencemark|textordfeminine|textordmasculine|textmarried|textdivorced|textbar|textbardbl|textbrokenbar|textbigcircle|textcopyright|copyright|textcircledP|textregistered|textservicemark|texttrademark|textnumero|textrecipe|textestimated|textmusicalnote|textdiscount|small|Large|textit|textsf|underline|textsl|tiny|footnotesize|normalsize|textsc|appendix|url)/im
```

For, i analysed a few files and keywords are as follows VBA keywords are as follows:

```regex
/(\b|^|\s)(#(if|else|end if)|VB_(NAME|GLOBALNAMESPACE|CREATABLE|PREDECLAREDID|EXPOSED|Description)|if|then|elseif|else|end|exit|for|each|to|next|select|case|do|loop|until|while|wend|public|private|friend|declare|ptrsafe|lib|type|enum|function|sub|Property|Get|Let|Set|byval|byref|Call|const|dim|static|as|not|Long|Double|String|Integer|With|Is|New|Attribute)\b/im
```

So would the PR simply be:

```yml
- extensions: ['.cls']
  rules:
  - language: TeX
    pattern: '\\(documentclass|usepackage|setcounter|title|LaTeX|author|varheartsuit|date|begin|maketitle|end|section|item|texttt|textbackslash|symbol|verb|char|bigskip|noindent|textcelsius|textdegree|ref|TeX|par|newline|dots|slash|subsection|medbreak|fbox|mbox|emph|smallbreak|bigbreak|makebox|framebox|textbf|parbox|llap|rlap|smash|hphantom|vphantom|phantom|marginpar|huge|negthinspace|thinspace|enspace|quad|qquad|hspace|label|aligned|of|raggedleft|frame|setlength|unitlength|put|vector|circle|thicklines|line|thinlines|sqrt|displaystyle|frac|linethickness|multiput|oval|qbezier|int_|infty|hat|text|today|textalpha|textbeta|textgamma|textdelta|textepsilon|textzeta|texteta|texttheta|textiota|textkappa|textlambda|textmu|textnu|textxi|textomikron|textpi|textrho|textsigma|texttau|textupsilon|textphi|textchi|textpsi|textomega|texteuro|textcent|textsterling|pounds|textbaht|textcolonmonetary|textcurrency|textdong|textflorin|textlira|textnaira|textpeso|textwon|textyen|textzerooldstyle|textoneoldstyle|texttwooldstyle|textthreeoldstyle|textfouroldstyle|textfiveoldstyle|textsixoldstyle|textsevenoldstyle|texteightoldstyle|textnineoldstyle|textperthousand|perthousand|textpertenthousand|textonehalf|textthreequarters|textonequarter|textfractionsolidus|textdiv|texttimes|textminus|textpm|textsurd|textlnot|textasteriskcentered|textonesuperior|texttwosuperior|textthreesuperior|textleftarrow|textuparrow|textrightarrow|textdownarrow|checkmark|textreferencemark|textordfeminine|textordmasculine|textmarried|textdivorced|textbar|textbardbl|textbrokenbar|textbigcircle|textcopyright|copyright|textcircledP|textregistered|textservicemark|texttrademark|textnumero|textrecipe|textestimated|textmusicalnote|textdiscount|small|Large|textit|textsf|underline|textsl|tiny|footnotesize|normalsize|textsc|appendix|url)'
  - language: ObjectScript
    pattern: '^Class\s'
  - language: VBA
    pattern: '(\b|^|\s)(#(if|else|end if)|VB_(NAME|GLOBALNAMESPACE|CREATABLE|PREDECLAREDID|EXPOSED|Description)|if|then|elseif|else|end|exit|for|each|to|next|select|case|do|loop|until|while|wend|public|private|friend|declare|ptrsafe|lib|type|enum|function|sub|Property|Get|Let|Set|byval|byref|Call|const|dim|static|as|not|Long|Double|String|Integer|With|Is|New|Attribute)\b'
```

?
