### ISSUE TITLE
Helm

### ISSUE THREAD

**Issue by RobertKeyser** [github/linguist#6196]
## Language name

Helm

## URL of example repository

https://github.com/DataDog/helm-charts

## URL of syntax highlighting grammar

https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/syntaxes/helm.tmLanguage.json
https://helm.sh/docs/chart_template_guide/getting_started/
https://github.com/helm/helm/tree/main/pkg/lint/rules
https://helm.sh/docs/chart_best_practices/templates/

## Most popular extensions

* `.yaml` for chart files 
* `.tpl` for `_helpers.tpl`
* `.txt` for `NOTES.txt`

## Detected language
* Smarty
* Mustache

## Additional details
In my opinion, Helm should be its own language; however, Helm Charts _technically_ use the Go templates, so I would settle for that as well.

* https://github.com/github/linguist/issues/4905
* https://github.com/github/linguist/issues/4578

**Comment by RobertKeyser** [comment]
Thinking through the required updates... 

```yaml
Helm:
  type: programming
  color: '#0f1689'
  aliases:
  - helm chart
  - helm template
  extensions:
  - ".tpl"
  - ".yaml"
  - ".yml"
  filenames:
  - NOTES.txt
  - _helpers.tpl
  ace_mode: yaml
  codemirror_mode: yaml
  codemirror_mime_type: text/x-yaml
  tm_scope: source.helm
```

Some additional thoughts:
* Some of the Helm files are just pure YAML and should be classified as such, e.g. `Chart.yaml` and `values.yaml`
* Not sure if the `ace_mode` and `codemirror_mode` settings should be YAML, because Helm charts aren't perfect YAML.

I'm on a mac and I'm having issues getting Ruby set up properly, so I haven't been able to add the language yet.
